import { METADATA } from '@/data/metadata';
import { DATA } from '@/data/resume';

export const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@id': `${DATA.url}#person`,
      '@type': 'Person',
      address: {
        '@type': 'PostalAddress',
        addressCountry: 'PK',
        addressLocality: 'Mandi Bahauddin',
        addressRegion: 'Punjab',
      },
      description: DATA.description,
      email: DATA.contact.email,
      image: METADATA.ogImage,
      jobTitle: DATA.role,
      knowsAbout: [
        'JavaScript',
        'TypeScript',
        'React.js',
        'Next.js',
        'Vue.js',
        'Nuxt.js',
        'Angular',
        'Node.js',
        'NestJS',
        'PostgreSQL',
        'MySQL',
        'Redis',
        'Docker',
        'Git',
        'TailwindCSS',
        'Full Stack Development',
        'Web Performance',
        'UI/UX',
      ],
      name: DATA.name,
      sameAs: [
        DATA.contact.social.GitHub.url,
        DATA.contact.social.LinkedIn.url,
        DATA.contact.social.Twitter.url,
      ],
      url: DATA.url,
      worksFor: {
        '@type': 'Organization',
        name: DATA.work[0].company,
        url: DATA.work[0].href,
      },
    },
    {
      '@id': `${DATA.url}#website`,
      '@type': 'WebSite',
      author: { '@id': `${DATA.url}#person` },
      description: METADATA.description,
      inLanguage: 'en-US',
      name: DATA.name,
      url: DATA.url,
    },
    {
      '@id': `${DATA.url}#webpage`,
      '@type': 'ProfilePage',
      about: { '@id': `${DATA.url}#person` },
      dateModified: new Date().toISOString().split('T')[0],
      description: METADATA.description,
      inLanguage: 'en-US',
      isPartOf: { '@id': `${DATA.url}#website` },
      name: METADATA.title,
      url: DATA.url,
    },
  ],
};
